Clean-MVP
elagarrigue/AyDS23-Lisboa3 pull request #3
Opened 2023-05-10 14:20 UTC by GonzaP14

2023-05-11 18:14 UTC, elagarrigue requested changes
- Muy bien la estructura y comunicación entre módulos 👍🏽 
- Recordar asignar el reviewer
- Más detalle en la descripción del PR
- Diagrama:
    - Faltan relaciones en presentation (dependencia de los helpers). Si no se definen, implica que todos lo utilizan
    - Englobar todo en un paquete `moredetails`
    - Agregar el servicio externo lastFM

2023-05-11 18:14 UTC, elagarrigue commented on app/src/main/kotlin/ayds/lisboa/songinfo/moredetails/presentation/OtherInfoView.kt
> +        artistInfoTextView = findViewById(R.id.textPane2)
Renombrar este id

2023-05-11 18:14 UTC, elagarrigue commented on app/src/main/kotlin/ayds/lisboa/songinfo/moredetails/presentation/HtmlHelper.kt
> +class HtmlHelperImpl: HtmlHelper {
internal

2023-05-11 18:14 UTC, elagarrigue commented on app/src/main/kotlin/ayds/lisboa/songinfo/moredetails/domain/ArtistInfoRepository.kt
> +interface ArtistInfoRepository {
mover a un paquete `repository`

2023-05-11 18:14 UTC, elagarrigue commented on app/src/main/kotlin/ayds/lisboa/songinfo/moredetails/domain/ArtistInfo.kt
>  sealed class ArtistInfo {
mover a un paquete `entities`

2023-05-11 20:18 UTC, GonzaP14 commented
Ahí asigne el reviewer Ema, mil disculpas...
Seguramente mañana ya implementamos los cambios y volvemos a mandar el PR.

2023-05-12 17:55 UTC, elagarrigue requested changes
Sigue en progreso, volver a hacer el re request cuando esté listo para ser revisado

2023-05-12 20:07 UTC, elagarrigue approved these changes
🏅

2023-05-12 20:07 UTC, merged